sudo: required
services:
 - docker

before_install:
 - docker build -t nelsoncastro/calculator_test -f Dockerfile.dev .
 - pip install poethepoet


script:
 - docker run nelsoncastro/calculator_test
 - poe checks
