FROM python:3.11-buster

RUN pip install poetry==1.8.2
RUN pip install poethepoet==0.25.1

WORKDIR /code_test

COPY pyproject.toml poetry.lock .pre-commit-config.yaml ./

RUN poetry install

COPY calculator_api ./calculator_api/

COPY tests ./tests/

CMD ["poetry", "run", "pytest", "-vvv"]
