name: Deploy to Digital Ocean

on:
  workflow_run:
    workflows: ["Docker Build and Test"]  # Remplacer par le nom du premier workflow
    types:
      - completed
    branches:
      - master


jobs:
  build-and-push-image:
    name: Build Docker dev Image before push
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push main image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculator-api:latest

  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: executing remote ssh commands using ssh key on digital ocean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        key: ${{ secrets.DIGITAL_OCEAN_KEY }}
        script: |
          # Login to Docker in my ssh user
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          # Stop and remove any existing container
          docker stop fastapi_container || true && docker rm fastapi_container || true

          # Pull the latest version of the image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/calculator-api:latest

          # Run container with specific name
          docker run --name fastapi_container -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/calculator-api:latest
