name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Bump version"]  # Remplacer par le nom du premier workflow
    types:
      - completed
    branches:
      - master


jobs:
  pypi-published:
    name: Run pre commit checks
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Build package
      run: poetry build

    - name: Publish package
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi ${PYPI_API_TOKEN}
        poetry publish
