name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Bump version"]  # Remplacer par le nom du premier workflow
    types:
      - completed
    branches:
      - master


jobs:
  pypi-published:
    name: Publishing to PyPI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
        #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory

    - name: Build package
      run: |
        poetry version ${{ steps.previoustag.outputs.tag }}
        poetry build

    - name: Publish package
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi ${PYPI_API_TOKEN}
        poetry publish
